version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092  # Bind Kafka to all interfaces
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092  # External address for other services/clients
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181  # Connect to Zookeeper
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
